//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WordAutomationDemo.Common.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully..
        /// </summary>
        public static string Added {
            get {
                return ResourceManager.GetString("Added", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} already exists..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been approved  successfully..
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company created successfully..
        /// </summary>
        public static string CompanyCreated {
            get {
                return ResourceManager.GetString("CompanyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company deleted successfully..
        /// </summary>
        public static string CompanyDeleted {
            get {
                return ResourceManager.GetString("CompanyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company updated successfully..
        /// </summary>
        public static string CompanyEdited {
            get {
                return ResourceManager.GetString("CompanyEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company not found..
        /// </summary>
        public static string CompanyNotFound {
            get {
                return ResourceManager.GetString("CompanyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been completed successfully..
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file you uploaded is corrupted..
        /// </summary>
        public static string corruptedFile {
            get {
                return ResourceManager.GetString("corruptedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task has been declined successfully..
        /// </summary>
        public static string Declined {
            get {
                return ResourceManager.GetString("Declined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been deleted successfully..
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has been generated successfully..
        /// </summary>
        public static string DocCreated {
            get {
                return ResourceManager.GetString("DocCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents added successfully..
        /// </summary>
        public static string DocumentAdded {
            get {
                return ResourceManager.GetString("DocumentAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry! The record has been deleted from the system..
        /// </summary>
        public static string Drop {
            get {
                return ResourceManager.GetString("Drop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, please contact your system administrator for support..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded document not valid. Please download and upload the document again. .
        /// </summary>
        public static string ExcelNotUploaded {
            get {
                return ResourceManager.GetString("ExcelNotUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is inactive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} link is invalid..
        /// </summary>
        public static string InvalidLink {
            get {
                return ResourceManager.GetString("InvalidLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Website URL..
        /// </summary>
        public static string InValidWebURL {
            get {
                return ResourceManager.GetString("InValidWebURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more {0} are in use..
        /// </summary>
        public static string IsInUse {
            get {
                return ResourceManager.GetString("IsInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only {1} characters allowed for {0}..
        /// </summary>
        public static string MaxAllowedLength {
            get {
                return ResourceManager.GetString("MaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} must be {2} to {1} characters long..
        /// </summary>
        public static string MinMaxAllowedLength {
            get {
                return ResourceManager.GetString("MinMaxAllowedLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password can not be same as old password..
        /// </summary>
        public static string NewPasswordCanNotBeSame {
            get {
                return ResourceManager.GetString("NewPasswordCanNotBeSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been added successfully. Email was not sent successfully..
        /// </summary>
        public static string NoEmailSent {
            get {
                return ResourceManager.GetString("NoEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least one checkbox to delete..
        /// </summary>
        public static string NoSelect {
            get {
                return ResourceManager.GetString("NoSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to view requested page..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string NotExistsUser {
            get {
                return ResourceManager.GetString("NotExistsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record already processed..
        /// </summary>
        public static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project created successfully..
        /// </summary>
        public static string ProjectCreated {
            get {
                return ResourceManager.GetString("ProjectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project deleted successfully..
        /// </summary>
        public static string ProjectDeleted {
            get {
                return ResourceManager.GetString("ProjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project updated successfully.
        /// </summary>
        public static string ProjectEdited {
            get {
                return ResourceManager.GetString("ProjectEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project not found..
        /// </summary>
        public static string ProjectNotFound {
            get {
                return ResourceManager.GetString("ProjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide all required fields..
        /// </summary>
        public static string ProvideAllFields {
            get {
                return ResourceManager.GetString("ProvideAllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record not found.
        /// </summary>
        public static string RecordNotFound {
            get {
                return ResourceManager.GetString("RecordNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is required..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password email has been sent to your registered email address..
        /// </summary>
        public static string ResetPasswordMail {
            get {
                return ResourceManager.GetString("ResetPasswordMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role added successfully..
        /// </summary>
        public static string RoleAdded {
            get {
                return ResourceManager.GetString("RoleAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role deleted successfully..
        /// </summary>
        public static string RoleDeleted {
            get {
                return ResourceManager.GetString("RoleDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role not found..
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role updated successfully..
        /// </summary>
        public static string RoleUpdated {
            get {
                return ResourceManager.GetString("RoleUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PPT has been saved successfully..
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section has been created successfully..
        /// </summary>
        public static string SectionCreated {
            get {
                return ResourceManager.GetString("SectionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section deleted successfully..
        /// </summary>
        public static string SectionDeleted {
            get {
                return ResourceManager.GetString("SectionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section has been updated successfully..
        /// </summary>
        public static string SectionEdited {
            get {
                return ResourceManager.GetString("SectionEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section not found..
        /// </summary>
        public static string SectionNotFound {
            get {
                return ResourceManager.GetString("SectionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} status has been changed successfully..
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been changed successfully..
        /// </summary>
        public static string SuccessChanged {
            get {
                return ResourceManager.GetString("SuccessChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been successfully logged out from the system..
        /// </summary>
        public static string SuccessLogOut {
            get {
                return ResourceManager.GetString("SuccessLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been reset successfully..
        /// </summary>
        public static string SuccessResetPassword {
            get {
                return ResourceManager.GetString("SuccessResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has been updated successfully..
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document has been uploaded successfully..
        /// </summary>
        public static string Uploaded {
            get {
                return ResourceManager.GetString("Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login credentials..
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
