//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignedExcelSheet
    {
        public int AssignedExcelSheetID { get; set; }
        public int AssignmentID { get; set; }
        public string SheetName { get; set; }
        public int Sequence { get; set; }
        public string SheetRemarks { get; set; }
        public bool IsSheetApproved { get; set; }
        public bool IsSheetModified { get; set; }
        public bool IsGrayedOut { get; set; }
    
        public virtual tblAssignment tblAssignment { get; set; }
    }
}
