//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignedWordPage
    {
        public int AssignedWordPageID { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public string DocName { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public Nullable<bool> ReviewRequested { get; set; }
        public string PageRemarks { get; set; }
        public virtual tblAssignment tblAssignment { get; set; }
        public string Ticks { get; set; }
    }
}
