//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignmentHistory
    {
        public int AssignmentHistoryID { get; set; }
        public Nullable<int> AssignmentLogID { get; set; }
        public string DocumentName { get; set; }
        public string Comments { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblAssignmentLog tblAssignmentLog { get; set; }
        public virtual tblUserDepartment tblUserDepartment { get; set; }
    }
}
