//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignmentMember
    {
        public int Id { get; set; }
        public bool CanEdit { get; set; }
        public bool CanApprove { get; set; }
        public Nullable<bool> CanPublish { get; set; }
        public Nullable<int> AssignmentID { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual tblAssignment tblAssignment { get; set; }
        public virtual tblUserDepartment tblUserDepartment { get; set; }
    }
}
