//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssignment()
        {
            this.tblAssignedWordPages = new HashSet<tblAssignedWordPage>();
            this.tblAssignedExcelSheets = new HashSet<tblAssignedExcelSheet>();
            this.tblAssignmentLogs = new HashSet<tblAssignmentLog>();
            this.tblAssignmentMembers = new HashSet<tblAssignmentMember>();
            this.tblExcelRowMaps = new HashSet<tblExcelRowMap>();
        }
    
        public int AssignmentID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public string Content { get; set; }
        public string ReplacementCode { get; set; }
        public int Action { get; set; }
        public Nullable<int> DocumentType { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public string Comments { get; set; }
        public string Remarks { get; set; }
        public string OrginalSourceFile { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> MainAssignmentID { get; set; }
        public Nullable<int> LockedByUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignedWordPage> tblAssignedWordPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignedExcelSheet> tblAssignedExcelSheets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignmentLog> tblAssignmentLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssignmentMember> tblAssignmentMembers { get; set; }
        public virtual tblAssignment tblAssignments1 { get; set; }
        public virtual tblAssignment tblAssignment1 { get; set; }
        public virtual tblProject tblProject { get; set; }
        public virtual tblDocument tblDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblExcelRowMap> tblExcelRowMaps { get; set; }
        public virtual tblUserDepartment LockedBy { get; set; }
        public Nullable<bool> IsEntireDocument { get; set; }
    }
}
