//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignedPPTSlide
    {
        public int AssignedPPTSildeID { get; set; }
        public int AssignmentID { get; set; }
        public string SlideName { get; set; }
        public int Sequence { get; set; }
        public string PPTRemarks { get; set; }
        public Nullable<bool> IsPPTApproved { get; set; }
        public Nullable<bool> IsTaskPPT { get; set; }
        public Nullable<int> AssignedDocsID { get; set; }
        public Nullable<bool> IsPPTModified { get; set; }
        public Nullable<bool> IsGrayedOut { get; set; }
        public Nullable<bool> ReviewRequested { get; set; }
        public Nullable<bool> IsPublished { get; set; }
    }
}
