//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExcelSheet
    {
        public int ExcelSheetID { get; set; }
        public string SheetName { get; set; }
        public string MasterDocumentName { get; set; }
        public int Sequence { get; set; }
        public Nullable<bool> IsOriginal { get; set; }
    }
}
