//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblExcelRowMap
    {
        public int Id { get; set; }
        public System.Guid RowId { get; set; }
        public string MasterDocumentName { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateLastModified { get; set; }
        public bool IsRemoved { get; set; }
        public int AssignmentID { get; set; }
    
        public virtual tblAssignment tblAssignment { get; set; }
    }
}
