//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLogActivity
    {
        public int LogActivityID { get; set; }
        public int LogActivityTypeID { get; set; }
        public string ActivityDetails { get; set; }
        public string IPAddress { get; set; }
        public Nullable<int> ChangedID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string MenuItem { get; set; }
        public Nullable<int> CompanyID { get; set; }
    }
}
