//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProjectDocument
    {
        public int ProjectDocumentID { get; set; }
        public int DocumentID { get; set; }
        public int ProjectID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual tblDocument tblDocument { get; set; }
        public virtual tblProject tblProject { get; set; }
    }
}
