//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSectionMaster
    {
        public int SectionID { get; set; }
        public string SectionName { get; set; }
        public string SectionURL { get; set; }
        public string Description { get; set; }
        public int ContentType { get; set; }
        public string ContentFile { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual tblCompany tblCompany { get; set; }
        public virtual tblUserDepartment tblUserDepartment { get; set; }
    }
}
