//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WordAutomationDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemplateMaster
    {
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
        public int TemplateType { get; set; }
        public string Subject { get; set; }
        public string TemplateContent { get; set; }
        public bool IsActive { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual tblUserDepartment tblUserDepartment { get; set; }
        public virtual tblUserDepartment tblUserDepartment1 { get; set; }
    }
}
